name: traffic-analytics

services:
  analytics-service:
    image: local/traffic-analytics:development
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    env_file:
      - .env

  test:
    image: local/traffic-analytics:development
    pull_policy: never
    command: ["yarn", "test"]
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    env_file:
      - .env
    tty: true
    profiles: [testing]

  lint:
    image: local/traffic-analytics:development
    pull_policy: never
    command: ["yarn", "lint"]
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    env_file:
      - .env
    tty: true
    profiles: [testing]


volumes:
  node_modules_volume:
