# Local development overrides
# This file is automatically loaded by `docker compose` for local development
# It adds bind mounts and volumes that are needed for live code reloading

services:
  analytics-service:
    volumes:
      - .:/app

  worker:
    volumes:
      - .:/app

  test:
    volumes:
      - .:/app

  lint:
    volumes:
      - .:/app

  e2e-test:
    volumes:
      - .:/app
