# Override file to allow running Ghost locally against the analytics service in this repo
# Usage: `docker compose -f compose.yml -f compose.ghost.yml -f compose.override.yml up`

services:
  analytics-service:
    volumes:
      - ghost-shared-config:/mnt/shared-config:ro
    networks:
      ghost:
        aliases:
          - traffic-analytics-local
  worker:
    volumes:
      - ghost-shared-config:/mnt/shared-config:ro
    networks:
      - ghost

volumes:
  ghost-shared-config:
    external: true
    name: ghost-dev_shared-config

networks:
  ghost:
    external: true
    name: ghost_dev
