name: traffic-analytics

services:
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: development
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    env_file:
      - .env

volumes:
  node_modules_volume:
