# Override file to allow running Ghost locally against the analytics service in this repo
# Usage: Start Ghost with `pnpm dev:analytics:local`, then run `pnpm dev:ghost`

services:
  analytics-service:
    volumes:
      - ghost-shared-config:/mnt/shared-config:ro
    networks:
      ghost:
        aliases:
          - traffic-analytics-local
  worker:
    volumes:
      - ghost-shared-config:/mnt/shared-config:ro
    networks:
      - ghost

volumes:
  ghost-shared-config:
    external: true
    name: ghost-dev_shared-config

networks:
  ghost:
    external: true
    name: ghost_dev
