name: traffic-analytics-proxy

services:
  traffic-analytics-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: development
    command: ["yarn", "dev:watch"]
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
