name: traffic-analytics

services:
  firestore:
    image: google/cloud-sdk:emulators
    command: ["gcloud", "emulators", "firestore", "start", "--host-port=0.0.0.0:8080"]
    ports:
      - 8080:8080
    environment:
      - FIRESTORE_PROJECT_ID=traffic-analytics-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 5

  analytics-service:
    image: local/traffic-analytics:development
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    env_file:
      - .env
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - FIRESTORE_PROJECT_ID=traffic-analytics-dev
    depends_on:
      firestore:
        condition: service_healthy

  test:
    image: local/traffic-analytics:development
    pull_policy: never
    command: sh -c "yarn test && yarn lint"
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    env_file:
      - .env
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - FIRESTORE_PROJECT_ID=traffic-analytics-dev
    tty: true
    profiles: [testing]
    depends_on:
      firestore:
        condition: service_healthy

  lint:
    image: local/traffic-analytics:development
    pull_policy: never
    command: ["yarn", "lint"]
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    env_file:
      - .env
    tty: true
    profiles: [testing]


volumes:
  node_modules_volume:
