name: "Slack Healthcheck Failed"
description: "Send a Slack notification when healthchecks fail after deployment"

inputs:
  environment:
    description: "The deployment environment (staging/production)"
    required: true
  environment_name:
    description: "Specific environment name (e.g., staging-subdomain)"
    required: true
  base_url:
    description: "The URL that was health checked"
    required: true
  webhook_url:
    description: "Slack webhook URL"
    required: true

runs:
  using: composite
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ inputs.webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          text: "Analytics Service Health Check Failed After ${{ inputs.environment == 'production' && 'Production' || 'Staging' }} Deployment"
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: ":rotating_light: *Analytics Service Health Check Failed After ${{ inputs.environment == 'production' && 'Production' || 'Staging' }} Deployment*"
            - type: "section"
              fields:
                - type: "mrkdwn"
                  text: "*Environment:*\n:computer: ${{ inputs.environment_name }}"
                - type: "mrkdwn"
                  text: "*Target URL:*\n:globe_with_meridians: ${{ inputs.base_url }}"
                - type: "mrkdwn"
                  text: "*Workflow:*\n:gear: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
          attachments:
            - color: "danger"
              fallback: "Analytics Service Health Check Failed After ${{ inputs.environment == 'production' && 'Production' || 'Staging' }} Deployment"
