name: "Extract Docker Node Version"
description: "Get the node version from the docker file"

outputs:
  node-version:
    description: The node version specified in the docker file
    value: ${{ steps.node-version.outputs.node_version }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Extract Node version from Dockerfile
      id: node-version
      shell: bash
      run: |
        NODE_VERSION=$(grep -oP 'ARG NODE_VERSION=\K[0-9]+' Dockerfile)
        echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
