name: "Docker build"
description: "Build docker image of project"

inputs:
  node-version:
    description: The node version to build the image on
    required: true
  image-name:
    description: What to tag the built image as
    required: true
    default: traffic-analytics:latest
  target:
    description: The build target (development or production)
    required: false
    default: development

outputs:
  image-name:
    description: The tag used for the built image
    value: ${{ inputs.image-name }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      id: build-docker-image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ inputs.image-name }}
        target: ${{ inputs.target }}
        build-args: |
          NODE_VERSION=${{ inputs.node-version }}
