name: "Lint & Test"
description: "Lint and test the codebase"

inputs:
  docker-image:
    description: Which docker image to run linting and testing on
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    # Lint
    - name: Lint
      shell: bash
      run: |
        export DOCKER_IMAGE=${{ inputs.docker-image }}
        docker compose -f compose.yml -f ${{ github.action_path }}/compose.ci.yml run --rm test yarn _lint

    # Test with compose (includes Firestore emulator)
    - name: Test
      shell: bash
      run: |
        export DOCKER_IMAGE=${{ inputs.docker-image }}
        docker compose -f compose.yml -f ${{ github.action_path }}/compose.ci.yml run --rm test

    - name: Stop services
      shell: bash
      run: |
        export DOCKER_IMAGE=${{ inputs.docker-image }}
        docker compose -f compose.yml -f ${{ github.action_path }}/compose.ci.yml down

    # E2E Test
    - name: Start services for E2E tests
      env:
        COMPOSE_PROFILES: batch,proxy
      shell: bash
      run: |
        export DOCKER_IMAGE=${{ inputs.docker-image }}
        docker compose -f compose.yml -f ${{ github.action_path }}/compose.ci.yml up -d
        
    - name: Run E2E tests
      env:
        COMPOSE_PROFILES: batch,proxy
        PROXY_TARGET: http://fake-tinybird:8080/v0/events
      shell: bash
      run: |
        export DOCKER_IMAGE=${{ inputs.docker-image }}
        docker compose -f compose.yml -f ${{ github.action_path }}/compose.ci.yml run --rm e2e-test

    # Copy coverage report from test container
    - name: Copy coverage report
      shell: bash
      run: |
        export DOCKER_IMAGE=${{ inputs.docker-image }}
        CONTAINER_ID=$(docker compose -f compose.yml -f ${{ github.action_path }}/compose.ci.yml ps -q test | head -1)
        if [ ! -z "$CONTAINER_ID" ]; then
          if docker cp $CONTAINER_ID:/app/coverage/cobertura-coverage.xml .; then
            echo "Coverage report copied successfully"
          else
            echo "Warning: No coverage file found"
          fi
        fi

    # Upload coverage reports
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success() && inputs.node-version == 20
      with:
        files: ./cobertura-coverage.xml
        fail_ci_if_error: false

    # Cleanup compose services
    - name: Cleanup compose services
      shell: bash
      if: always()
      run: |
        export DOCKER_IMAGE=${{ inputs.docker-image }}
        docker compose -f compose.yml -f ${{ github.action_path }}/compose.ci.yml down
