name: "Lint & Test"
description: "Lint and test the codebase"

inputs:
  docker-image:
    description: Which docker image to run linting and testing on
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Generate UUID
      shell: bash
      run: echo "UUID=$(uuidgen)" >> $GITHUB_ENV

    # Start container
    - name: Start container
      shell: bash
      run: docker run -d --label "uuid=${{ env.UUID }}" ${{ inputs.docker-image }}

    # Get container ID and put in environment variable for later use
    - name: Get container ID
      shell: bash
      run: echo "CONTAINER_ID=$(docker ps --filter "label=uuid=${{ env.UUID }}" -q)" >> $GITHUB_ENV

    # Lint
    - name: Lint
      shell: bash
      run: docker exec ${{ env.CONTAINER_ID }} yarn lint

    # Test
    - name: Test
      shell: bash
      run: docker exec ${{ env.CONTAINER_ID }} yarn test

    # Copy coverage report out of container
    - shell: bash
      run: docker cp ${{ env.CONTAINER_ID }}:/app/coverage/cobertura-coverage.xml .

    # Upload coverage reports
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success() && inputs.node-version == 20
      with:
        files: ./cobertura-coverage.xml
        fail_ci_if_error: false

    # Shutdown and remove container
    - name: Shutdown and remove container
      shell: bash
      if: always()
      run: docker rm -f ${{ env.CONTAINER_ID }}
