# CI override that extends the base compose.yml
# This removes volumes and bind mounts while using pre-built images

services:
  # Override emulator services to use CI-specific project name
  firestore:
    environment:
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci

  pubsub:
    environment:
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci
      - PUBSUB_TOPIC_PAGE_HITS_RAW=traffic-analytics-page-hits-raw
      - PUBSUB_SUBSCRIPTION_PAGE_HITS_RAW=traffic-analytics-page-hits-raw-sub

  # Override lint service to use pre-built development image
  lint:
    image: ${DOCKER_IMAGE_DEVELOPMENT}
    environment:
      - NODE_ENV=testing
    networks:
      - dev-network
    profiles: []

  # Override test service to use pre-built development image and CI configuration
  test:
    image: ${DOCKER_IMAGE_DEVELOPMENT}
    command: ["yarn", "test"]
    environment:
      - NODE_ENV=testing
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PUBSUB_TOPIC_PAGE_HITS_RAW=traffic-analytics-page-hits-raw
      - PUBSUB_SUBSCRIPTION_PAGE_HITS_RAW=traffic-analytics-page-hits-raw-sub
      - FIRESTORE_DATABASE_ID=(default)
      - FIRESTORE_SALT_COLLECTION=salts
      - GOOGLE_APPLICATION_CREDENTIALS=/dev/null
    networks:
      - dev-network
    profiles: []
    depends_on:
      firestore:
        condition: service_healthy
      pubsub:
        condition: service_healthy

  # Override analytics-service to use production image for E2E tests
  analytics-service:
    image: ${DOCKER_IMAGE_PRODUCTION}
    environment:
      - NODE_ENV=production
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PUBSUB_TOPIC_PAGE_HITS_RAW=traffic-analytics-page-hits-raw
      - GOOGLE_APPLICATION_CREDENTIALS=/dev/null
      - PROXY_TARGET=http://fake-tinybird:8080/v0/events
    networks:
      - dev-network
    depends_on:
      firestore:
        condition: service_healthy
      pubsub:
        condition: service_healthy
      fake-tinybird:
        condition: service_healthy

  # Override e2e-test service to use development image (needs vitest) but test against production services
  e2e-test:
    image: ${DOCKER_IMAGE_DEVELOPMENT}
    command: ["yarn", "test:e2e"]
    environment:
      - NODE_ENV=testing
      - ANALYTICS_SERVICE_URL=http://analytics-service:3000
      - WIREMOCK_URL=http://fake-tinybird:8080
    networks:
      - dev-network
    profiles: []
    depends_on:
      analytics-service:
        condition: service_started
      fake-tinybird:
        condition: service_healthy