# CI override that extends the base compose.yml
# This removes volumes and bind mounts while using pre-built images

services:
  # Override emulator services to use CI-specific project name

  analytics-service:
    image: ${DOCKER_IMAGE}
    build: {}  # Disable build in CI
    environment:
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci

  worker:
    image: ${DOCKER_IMAGE}
    build: {}  # Disable build in CI
    environment:
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci
      - TINYBIRD_TRACKER_TOKEN=test-token

  analytics-service-proxy:
    image: ${DOCKER_IMAGE}
    build: {}  # Disable build in CI
    environment:
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci
      - TINYBIRD_TRACKER_TOKEN=test-token

  firestore:
    environment:
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci

  pubsub:
    environment:
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci
      - PUBSUB_TOPIC_PAGE_HITS_RAW=traffic-analytics-page-hits-raw
      - PUBSUB_SUBSCRIPTION_PAGE_HITS_RAW=traffic-analytics-page-hits-raw-sub

  

  # Override test service to use pre-built image and CI configuration
  test:
    image: ${DOCKER_IMAGE}
    command: ["yarn", "_test"]
    environment:
      - NODE_ENV=testing
      - GOOGLE_CLOUD_PROJECT=traffic-analytics-ci
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PUBSUB_TOPIC_PAGE_HITS_RAW=traffic-analytics-page-hits-raw
      - PUBSUB_SUBSCRIPTION_PAGE_HITS_RAW=traffic-analytics-page-hits-raw-sub
      - FIRESTORE_DATABASE_ID=(default)
      - FIRESTORE_SALT_COLLECTION=salts
      - GOOGLE_APPLICATION_CREDENTIALS=/dev/null
    networks:
      - dev-network
    profiles: []
    depends_on:
      firestore:
        condition: service_healthy
      pubsub:
        condition: service_healthy

  # Override e2e-test service to use pre-built image and CI configuration
  e2e-test:
    image: ${DOCKER_IMAGE}
    command: ["yarn", "_test:e2e"]
    environment:
      - NODE_ENV=testing
      - ANALYTICS_SERVICE_URL=http://analytics-service:3000
      - WIREMOCK_URL=http://fake-tinybird:8080
    networks:
      - dev-network
    profiles: []
