name: traffic-analytics-ci

services:
  firestore:
    image: google/cloud-sdk:emulators
    command: ["gcloud", "emulators", "firestore", "start", "--host-port=0.0.0.0:8080"]
    ports:
      - 8080:8080
    environment:
      - FIRESTORE_PROJECT_ID=traffic-analytics-ci
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 5

  pubsub:
    image: google/cloud-sdk:emulators
    command: ["/app/start-pubsub.sh"]
    ports:
      - 8085:8085
    volumes:
      - ../../docker/pubsub/start-pubsub.sh:/app/start-pubsub.sh:ro
    environment:
      - PUBSUB_PROJECT_ID=traffic-analytics-ci
      - PUBSUB_PORT=8085
      - PUBSUB_TOPIC_PAGE_HITS_RAW=traffic-analytics-page-hits-raw
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8085 && test -f /tmp/pubsub-ready"]
      interval: 5s
      timeout: 3s
      retries: 10

  lint:
    image: ${DOCKER_IMAGE}
    command: ["yarn", "lint"]
    environment:
      - NODE_ENV=testing

  test:
    image: ${DOCKER_IMAGE}
    command: ["yarn", "test"]
    environment:
      - NODE_ENV=testing
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - FIRESTORE_PROJECT_ID=traffic-analytics-ci
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PUBSUB_PROJECT_ID=traffic-analytics-ci
      - PUBSUB_TOPIC_PAGE_HITS_RAW=traffic-analytics-page-hits-raw
      - GOOGLE_APPLICATION_CREDENTIALS=/dev/null
    depends_on:
      firestore:
        condition: service_healthy
      pubsub:
        condition: service_healthy