name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      region:
        required: true
        type: string
      version:
        required: true
        type: string
      service:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy (${{ inputs.service }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: "Auth with Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          project_id: ghost-traffic-analytics
          token_format: access_token
          workload_identity_provider: projects/460065119042/locations/global/workloadIdentityPools/github-oidc-${{ contains(inputs.environment, 'staging') && 'stg' || 'prd' }}-ta/providers/github-provider-${{ contains(inputs.environment, 'staging') && 'stg' || 'prd' }}-ta
          service_account: ${{ contains(inputs.environment, 'staging') && 'stg' || 'prd' }}-gh-deploy@ghost-traffic-analytics.iam.gserviceaccount.com
      - name: "Deploy to Cloud Run"
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: europe-docker.pkg.dev/ghost-traffic-analytics/traffic-analytics/traffic-analytics:${{ inputs.version }}
          region: ${{ inputs.region }}
          service: ${{ inputs.service }}
          skip_default_labels: true
          labels: |-
            commit-sha=${{ github.sha }}
