name: Docker Hub Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.traffic-analytics-docker-metadata.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract node version
        id: extract-node-version
        uses: ./.github/actions/extract-node-version

      - name: Build Development Docker Image
        id: docker-build-dev
        uses: ./.github/actions/docker-build
        with:
          node-version: ${{ fromJSON(steps.extract-node-version.outputs.node-version) }}
          image-name: local/traffic-analytics:development
          target: development

      - name: Build Production Docker Image
        id: docker-build-prod
        uses: ./.github/actions/docker-build
        with:
          node-version: ${{ fromJSON(steps.extract-node-version.outputs.node-version) }}
          image-name: local/traffic-analytics:production
          target: production

      - name: Lint & Test
        uses: ./.github/actions/lint-and-test
        with:
          development-image: ${{ steps.docker-build-dev.outputs.image-name }}
          production-image: ${{ steps.docker-build-prod.outputs.image-name }}

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker Tags
        id: traffic-analytics-docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghost/traffic-analytics
          tags: |
            ${{ github.ref == 'refs/heads/main' && 'type=edge,branch=main' || '' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,priority=1100
            type=sha,format=long

      - name: Retag & Push Docker Image
        run: |
          for tag in $(echo "${{ steps.traffic-analytics-docker-metadata.outputs.tags }}"); do
            echo "Tagging: $tag"
            docker tag ${{ steps.docker-build-prod.outputs.image-name }} $tag
          done

          for tag in $(echo "${{ steps.traffic-analytics-docker-metadata.outputs.tags }}"); do
            echo "Pushing: $tag"
            docker push $tag
          done
