name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
          - staging
          - production
          - both
      tag:
        description: 'Docker tag (from GCP Artifact Registry) to rollback to'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  generate-environments:
    name: "Generate Environments"
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.generate-environments.outputs.environments }}
    steps:
      - name: Generate Environments
        id: generate-environments
        run: |
          case ${{ github.event.inputs.environment }} in
            both)
              echo 'environments=["staging", "production"]' >> $GITHUB_OUTPUT
              ;;
            production)
              echo 'environments=["production"]' >> $GITHUB_OUTPUT
              ;;
            staging)
              echo 'environments=["staging"]' >> $GITHUB_OUTPUT
              ;;
            *)
              echo 'environments=[]' >> $GITHUB_OUTPUT
              ;;
          esac

  rollback:
    name: Rollback (${{ matrix.environment }})
    needs: generate-environments
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.generate-environments.outputs.environments) }}
    uses: ./.github/workflows/deploy-environment.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      image: ${{ vars.DOCKER_IMAGE }}:${{ inputs.tag }}
      region: europe-west4
      region_name: netherlands
      services: '["analytics"]'
